from pydantic import BaseModel, Field

class ClinicianReview(BaseModel):

    patient_id: str = Field(
        ...,
        description="Unique patient identifier for audit tracking",
        example="patient_001"
    )

    model_risk_score: float = Field(
        ...,
        ge=0,
        le=1,
        description="Risk score generated by the AI model",
        example=0.82
    )

    decision_mode: str = Field(
        ...,
        description="System decision mode at time of review (SAFE / NORMAL / VERBOSE)",
        example="SAFE"
    )

    clinician_decision: str = Field(
        ...,
        description="Final clinician override decision",
        example="LOW_RISK_OVERRIDE"
    )

    clinician_notes: str = Field(
        ...,
        description="Clinician justification for override",
        example="Patient history suggests transient abnormality; recommend monitoring."
    )

    class Config:
        title = "Clinician Override Review Schema"